Repository rak517/Rolling, pull requests merged in 2024-12, with the labels that each got.

#5 feat: 공통 컴포넌트(Header, Button) 구현
  src/assets/icons/logo.svg
  src/components/layout/.gitkeep
  src/components/layout/Header.js
  src/components/ui/.gitkeep
  src/components/ui/Button.js
  src/pages/MainPage/MainPage.js
Labels: feat

#6 feat: detailPage.js의 기본 뼈대 작업
  src/components/layout/Header.js
  src/pages/DetailPage/DetailPage.js
Labels: feat

#10 feat: detailPage의 버튼 기능구현, 스크롤 기능 구현, 반응형에 따른 카드배치
  src/assets/icons/cardBtn.png
  src/pages/DetailPage/DetailPage.js
Labels: feat

#11 feat: 랜딩 페이지 구현 09
  src/assets/images/main-img-01.svg
  src/assets/images/main-img-02.svg
  src/components/layout/Header.js
  src/components/ui/Button.js
  src/pages/MainPage/CreatePaperIntro.js
  src/pages/MainPage/EmojiIntro.js
  src/pages/MainPage/MainPage.js
Labels: feat

#14 feat: detailpage의 수정하기 버튼 추가
  src/pages/DetailPage/DetailPage.js
Labels: feat

#16 feat/list-page-UI-13
  package-lock.json
  package.json
  public/assets/images/beige-bg.svg
  public/assets/images/blue-bg.svg
  public/assets/images/green-bg.svg
  public/assets/images/purple-bg.svg
  src/assets/icons/carousel-left.svg
  src/assets/icons/carousel-right.svg
  src/components/common/.gitkeep
  src/components/common/CarouselButton.js
  src/components/common/EmojiCard.js
  src/components/common/ProfileImages.js
  src/components/common/Reactions.js
  src/components/ui/Button.js
  src/data/mockData.json
  src/hooks/useCarousel.js
  src/hooks/useResponsive.js
  src/pages/ListPage/ListPage.js
  src/pages/ListPage/ListPage.styles.js
  src/pages/ListPage/ListPageCard.js
  src/pages/ListPage/ResponsiveCarousel.js
Labels: feat

#18 Refactor/responsive carousel custom #17
  package-lock.json
  package.json
  src/pages/ListPage/CarouselContainer.js
  src/pages/ListPage/CarouselPresenter.js
  src/pages/ListPage/ListPage.js
Labels: refactor

#21 feat: DetailPage 모달 기능 구현, Card 컴포넌트 UI 구현 및 스타일 분리
  package-lock.json
  package.json
  src/components/ui/Button.js
  src/pages/DetailPage/CardRealtion.js
  src/pages/DetailPage/DetaiPageModal.js
  src/pages/DetailPage/DetailPage.js
  src/pages/DetailPage/DetailPage.style.js
  src/pages/DetailPage/DetailPageCards.js
  src/pages/DetailPage/DetailPageData.js
  src/pages/DetailPage/DetailPageEditButton.js
  src/pages/DetailPage/DetailPageModal.style.js
Labels: feat

#22 feat: detailPage("/post")의 MessageStatusBar UI 구현 #19
  src/assets/icons/arrow_down.svg
  src/assets/icons/button-icon.svg
  src/assets/icons/share-button.svg
  src/components/common/Reactions.js
  src/components/layout/Header.js
  src/components/layout/MessageStatusBar/MessageStatusBar.style.js
  src/components/layout/MessageStatusBar/MessageStatusBarContainer.js
  src/components/layout/MessageStatusBar/MessageStatusBarPresenter.js
  src/components/ui/Button.js
  src/data/mockData.json
  src/pages/CreatePage/CreatePage.js
  src/pages/DetailPage/DetailPage.js
  src/pages/ListPage/ListPage.js
  src/pages/ListPage/ListPageCard.js
  src/pages/MainPage/MainPage.js
Labels: feat

#29 feat: listPage API 연동 및 데이터 표시 구현
  src/api/ListPage/fetchRecipientData.js
  src/index.js
  src/pages/ListPage/ListPageContainer.js
  src/pages/ListPage/ListPagePresenter.js
  src/utils/errorHandler.js
  src/utils/exceptions.js
Labels: feat

#33 feat/message status bar api #30
  .env.example
  src/api/DetailPage/fetchAddReaction.js
  src/api/DetailPage/fetchRecipientReactions.js
  src/api/DetailPage/fetchRecipientsById.js
  src/components/layout/MessageStatusBar/MessageStatusBar.style.js
  src/components/layout/MessageStatusBar/MessageStatusBarContainer.js
  src/components/layout/MessageStatusBar/MessageStatusBarPresenter.js
  src/hooks/useKakaoShare.js
  src/pages/DetailPage/DetailPage.js
Labels: feat

#35 fix: 카카오 SDK 초기화 오류 방지를 위해 index.html에서 직접 로드
  public/index.html
  src/hooks/useKakaoShare.js
Labels: fix

#39 feat/toast notification #36
  src/assets/icons/toast-cancel.svg
  src/assets/icons/toast-check.svg
  src/components/common/Toast/Toast.style.js
  src/components/common/Toast/ToastContainer.js
  src/components/common/Toast/ToastPresenter.js
  src/components/common/Toast/index.js
  src/components/layout/MessageStatusBar/MessageStatusBarContainer.js
Labels: feat

#43 Feat: detialPage api 연동, EditPage의 메세지, 롤링페이퍼 삭제 구현
  .env.example
  src/api/Editpage/fetchDeleteAllRolling.js
  src/api/Editpage/fetchDeleteMessage.js
  src/assets/icons/delete-btn.png
  src/components/layout/MessageStatusBar/MessageStatusBarPresenter.js
  src/pages/DetailPage/DetaiPageModal.js
  src/pages/DetailPage/DetailPage.js
  src/pages/DetailPage/DetailPage.style.js
  src/pages/DetailPage/DetailPageCards.js
  src/pages/DetailPage/DetailPageCards.style.js
  src/pages/DetailPage/DetailPageData.js
  src/pages/DetailPage/DetailPageEditButton.js
  src/pages/DetailPage/DetailPageModal.style.js
  src/pages/EditPage/EditPage.js
  src/pages/EditPage/EditPageAllDeleteButton.js
  src/pages/EditPage/EditPageCards.js
  src/pages/EditPage/EditPageCrads.style.js
  src/pages/EditPage/EditPageMessageDeleteBtn.js
Labels: feat

#56 fix: create main page 에러 수정
  q
  src/api/CreatePage/createRolling.js
  src/pages/CreatePage/CreateMainPage.js
  src/styles/CreatePage/BackgroundSection.styled.js
Labels: fix

#59 refactor: readme-setting
  README.md
Labels: refactor

#60 Fix: jsx파일 js파일로 수정
  src/pages/SendMessagePage/CreateButton.js
  src/pages/SendMessagePage/FontSelectionSection.js
  src/pages/SendMessagePage/FontSelectionSection.jsx
  src/pages/SendMessagePage/FromSection.js
  src/pages/SendMessagePage/FromSection.jsx
  src/pages/SendMessagePage/Header.js
  src/pages/SendMessagePage/Header.jsx
  src/pages/SendMessagePage/MessageContentSection.js
  src/pages/SendMessagePage/MessageContentSection.jsx
  src/pages/SendMessagePage/MessageForm.js
  src/pages/SendMessagePage/MessageForm.jsx
  src/pages/SendMessagePage/ProfileImageSection.js
  src/pages/SendMessagePage/ProfileImageSection.jsx
  src/pages/SendMessagePage/RelationshipSection.js
  src/pages/SendMessagePage/RelationshipSection.jsx
  src/styles/SendMessagePage/CreateButton.styled.js
  src/styles/SendMessagePage/FontSelectionSection.styled.js
  src/styles/SendMessagePage/FromSection.styled.js
  src/styles/SendMessagePage/Header.styled.js
  src/styles/SendMessagePage/MessageContentSection.styled.js
  src/styles/SendMessagePage/MessageForm.styled.js
  src/styles/SendMessagePage/ProfileImageSection.styled.js
  src/styles/SendMessagePage/RelationshipSection.styled.js
Labels: fix

#62 refactor: readme-gif추가
  README.md
  src/assets/icons/vercel.png
  src/assets/images/createRolling.gif
  src/assets/images/deleteMessage.gif
  src/assets/images/deleteRollinng.gif
  src/assets/images/emoji.gif
  src/assets/images/kakaoUrl.gif
  src/assets/images/mainPage.gif
  src/assets/images/messageCheck.gif
Labels: refactor

#64 Feat: create meesage api 구현 및 오류 수정
  README.md
  src/api/DetailPage/fetchRecipientsById.js
  src/api/SendMessagePage/sendMessage.js
  src/index.js
  src/pages/SendMessagePage/FromSection.js
  src/pages/SendMessagePage/Header.js
  src/pages/SendMessagePage/MessageForm.js
  src/pages/SendMessagePage/ProfileImageSection.js
  src/pages/SendMessagePage/SendMessagePage.js
  src/styles/SendMessagePage/RelationshipSection.styled.js
  src/styles/SendMessagePage/SendMessagePage.styled.js
Labels: feat, refactor

#68 refactor: detail-page styled 수정 및 favicon 추가
  public/favicon.ico
  src/pages/DetailPage/DetailPage.style.js
  src/pages/DetailPage/DetailPageEditButton.js
Labels: refactor

#69 refactor: create img UI 수정 65
  package-lock.json
  src/api/CreatePage/createRolling.js
  src/pages/CreatePage/CreateMainPage.js
  src/pages/CreatePage/ImageOptions.js
  src/pages/DetailPage/DetailPage.js
  src/pages/SendMessagePage/ProfileImageSection.js
Labels: refactor

#73 refactor: readme.md gif추가 및 컨베션 내용추가
  README.md
  package-lock.json
  src/assets/images/createMessage.gif
Labels: refactor

#75 Fix: create rolling시에 img error 해결 및 readme 배포링크 추가
  README.md
  src/pages/CreatePage/ImageOptions.js
Labels: fix

#78 refactor: readme 내용추가
  README.md
Labels: refactor
